from setuptools import find_packages, setup

setup(
    name='pilotpy',
    version='2.0.8',
    author='Mehdi Joodaki',
    author_email='judakimehdi@gmail.com',
    url='https://github.com/CostaLab/PILOT',
    python_requires='>=3.9',
    install_requires=[
            "cycler",
            "joypy",
            "leidenalg",
            "numpy",
            "matplotlib",
            "pandas",
            "plotly",
            "plotnine",
            "pot",
            "pydeseq2",
            "pydiffmap",
            "scanpy",
            "scikit-learn",
            "scikit-network",
            "scipy",
            "seaborn",
            "shap",
            "statsmodels",
            "elpigraph-python",
            "adjusttext",
            "gprofiler-official",
            "gseapy",
            "anndata", 
        ],
        packages=find_packages()
)
